# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
       - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Prepare java
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: latest 
          
      - name: Cache deps
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
                ${{ runner.os }}-maven-

      - name: Cache firebase
        uses: actions/cache@v1
        id: cache-firebase
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
                ${{ runner.os }}-firebase-
      
      - name: Run tests
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          FIRETOMIC_FIREBASE_AUTH: ${{ secrets.FIRETOMIC_FIREBASE_AUTH }}
        run: |
          clojure -M -e "*clojure-version*"
          mkdir -p ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          npm install -g firebase-tools@10.1.2
          bash bin/test.sh
          bash <(curl -s https://codecov.io/bash)
