# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
       - '*'
  pull_request:
    branches: 
       - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache deps
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
                ${{ runner.os }}-maven-

      - name: Cache firebase
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
                ${{ runner.os }}-firebase-
      
      - name: Run tests
        run: |
          mkdir -p ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          npm install -g firebase-tools@8.5.0
          bash unit.sh
          bash test.sh
